package ru.impression.state_machine.example.things_managing_process

enum class Event {
    FAVOURITE_THINGS_LOADED,
    FAVOURITE_THING_UNLIKED,
    FAVOURITE_THING_DELETED,
    RECOMMENDED_THINGS_REQUESTED,
    RECOMMENDED_THINGS_LOADED,
    RECOMMENDED_THING_LIKED,
    FAVOURITE_THING_ADDED,
    RECOMMENDED_THINGS_HIDE_REQUESTED
}